[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = ["cd backend && python3 -m pip3 install --upgrade pip3 && python3 -m pip3 install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python3 -m alembic upgrade head"]

[start]
cmd = "cd backend && python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

